name: "Deploy"

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - "site/**"

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 20

      - name: Setup pnpm
        run: npm i -g pnpm

      - name: Install dependencies
        run: pnpm i

      - name: Build Packages
        run: npm run build

      - name: Build Site
        run: npm run build:site

      - name: Ready to Upload
        run: |
          mv site/dist _site
          cp _site/index.html _site/404.html

      - name: Upload Artifact
        uses: actions/upload-pages-artifact@v2

  Deploy:
    runs-on: ubuntu-latest
    needs: Build

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v2
        id: deployment
